const siteConfig = {
  name: "Podgorica Airport Car Rental",
  tagline: "Gateway to Mountains, Lakes, and Coast",
  domain: "podgoricaairportcarrental.com",
  phone: "",
  email: "info@podgoricaairportcarrental.com",
  address: "Tabacina BB, Kotor, 85330",

  hero: {
    headline: "Podgorica Airport Car Rental \u2014 TGD",
    subheadline: "Collect your rental car at Podgorica Airport arrivals. Gateway to Durmitor, Lake Skadar, and Montenegro\u2019s Adriatic coast.",
    image: "/img/hero-podgorica.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      name: "VW Polo",
      category: "Economy",
      price: 25,
      image: "/img/pexels-1035108.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      popular: false,
    },
    {
      id: 2,
      slug: "skoda-octavia",
      name: "Skoda Octavia",
      category: "Mid-Size",
      price: 35,
      image: "/img/pexels-116675.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Automatic Transmission", "Cruise Control", "Parking Sensors", "Large Boot"],
      popular: true,
    },
    {
      id: 3,
      slug: "toyota-corolla",
      name: "Toyota Corolla",
      category: "Mid-Size",
      price: 38,
      image: "/img/pexels-170811.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Hybrid Engine", "Reversing Camera", "Apple CarPlay", "Keyless Start"],
      popular: false,
    },
    {
      id: 4,
      slug: "mercedes-c-class",
      name: "Mercedes C-Class",
      category: "Premium",
      price: 65,
      image: "/img/pexels-120049.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Leather Seats", "Navigation System", "Premium Sound", "Heated Seats"],
      popular: true,
    },
    {
      id: 5,
      slug: "jeep-renegade",
      name: "Jeep Renegade",
      category: "SUV",
      price: 55,
      image: "/img/pexels-1638459.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["4x4 Drive", "Hill Descent Control", "Roof Rails", "Off-Road Mode"],
      popular: false,
    },
    {
      id: 6,
      slug: "bmw-x3",
      name: "BMW X3",
      category: "Premium SUV",
      price: 85,
      image: "/img/pexels-892522.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Panoramic Roof", "Adaptive Cruise", "360 Camera", "Sport Mode"],
      popular: false,
    },
    {
      id: 7,
      slug: "fiat-500",
      name: "Fiat 500",
      category: "City",
      price: 20,
      image: "/img/pexels-1007410.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      popular: false,
    },
    {
      id: 8,
      slug: "vw-transporter",
      name: "VW Transporter",
      category: "Van",
      price: 70,
      image: "/img/pexels-2533092.jpg",
      seats: 9,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 6,
      ac: true,
      features: ["9 Seats", "Airport Shuttle Ready", "Sliding Doors", "Ample Storage"],
      popular: false,
    },
  ],

  features: [
    { icon: "map-pin", title: "Airport Pickup", description: "We meet you at TGD arrivals with your name on a board. Keys in hand, car parked outside the terminal \u2014 10-minute handover and you\u2019re on the road." },
    { icon: "shield-check", title: "Full Insurance", description: "CDW and theft cover included as standard. Upgrade to zero excess for total peace of mind on mountain passes and narrow coastal roads." },
    { icon: "clock", title: "24/7 Support", description: "Flight delayed to midnight? Flat tyre on the road to Zabljak? Call us any hour \u2014 we know every route from the airport outward." },
    { icon: "ban", title: "No Hidden Fees", description: "One transparent price covers insurance, VAT, and mileage. What you see when you book is exactly what you pay at pickup. Nothing added at the desk." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Flight changed? Mountain pass closed by snow? Cancel up to 7 days before collection for a full refund, no questions asked." },
    { icon: "globe", title: "Cross-Border Ready", description: "Albania is 45 minutes south. Croatia, Bosnia, Serbia, and Kosovo are all reachable. Green Card paperwork prepared at booking." },
  ],

  testimonials: [
    { name: "Lars & Ingrid", location: "Oslo, Norway", text: "We flew into Podgorica and drove straight to Durmitor. The car was waiting at the airport, paperwork took two minutes, and three hours later we were standing at the Black Lake trailhead. Returned through Ostrog Monastery on the way back. Could not have done any of it without the car.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Sophie Duval", location: "Lyon, France", text: "Podgorica surprised us. The riverside restaurants along the Moraca were excellent, and having a car meant we could visit Virpazar and Lake Skadar on the same afternoon. The drive through the canyon to Kolasin the next day was the highlight of our entire Balkans trip.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "The Kovacs Family", location: "Budapest, Hungary", text: "Picked up at Podgorica Airport and spent a week exploring. Cetinje, Skadar Lake, Niksic, and down to Budva for the beaches. The kids loved the winding mountain roads. Drop-off was effortless and the price was exactly what we were quoted online.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What documents do I need?", a: "Bring your driving licence, passport, and a physical credit card in the main driver\u2019s name. If your licence doesn\u2019t display Latin-script details, an International Driving Permit is also required." },
    { q: "Can I drive to Albania or Croatia?", a: "Albania is under an hour south via the Hani i Hotit crossing. Croatia is reachable via the coast or through Bosnia. We prepare the Green Card at booking for all neighbouring countries." },
    { q: "Is there a minimum age?", a: "Drivers must be at least 21 with a minimum of 2 years\u2019 experience. A young driver supplement applies for those under 25 \u2014 the exact amount varies by vehicle and is shown in the search results." },
    { q: "What is included in the price?", a: "Third Party Liability and CDW insurance are included in the base price for all vehicles, along with VAT and the mandatory safety kit. Unlimited mileage is available on most cars \u2014 check the vehicle card before booking." },
    { q: "How does pickup work at Podgorica Airport?", a: "Your agent meets you in the TGD arrivals hall holding a sign with your name. The car is parked directly outside the terminal. From the airport to the city centre takes around 15 minutes." },
    { q: "Can I drop off at a different location?", a: "One-way rentals are available across 28 pickup and dropoff points in Montenegro, including coastal towns. Select different locations at the booking stage and a one-way fee may apply depending on the distance." },
    { q: "What is the cancellation policy?", a: "Free cancellation is available up to 7 days before the rental start date. Luxury cars and convertibles require 30 days\u2019 notice. A 6% payment processing fee is applied to all cancellations regardless of timing." },
    { q: "Is a deposit required?", a: "Most vehicles require a deposit of 100\u2013350 EUR held on a physical credit card in the driver\u2019s name. Some budget cars are available with no deposit \u2014 these are clearly flagged in the search results. The hold is released when the vehicle is returned undamaged." },
    { q: "How long does it take to reach the coast?", a: "Budva is roughly 60 minutes via the Sozina tunnel. Kotor is about 90 minutes through the mountains via Cetinje, or 2 hours via the highway. Bar is around 50 minutes south." },
    { q: "Are there hidden costs?", a: "No. The price shown includes all taxes and fees. There are no airport surcharges, no fuel-policy surprises, and nothing added at the desk." },
    { q: "How much is the down payment?", a: "A deposit of 15\u201320% of the total rental cost is required to confirm your booking. The remaining balance is settled directly with the rental agent when you collect the car." },
    { q: "Can I rent without a credit card?", a: "A small number of vehicles in the fleet are available without a credit card. These options are clearly marked in the search results when you filter by pickup location." },
  ],

  locations: [
    { name: "Podgorica Airport", tag: "Most Popular" },
    { name: "City Centre", tag: "" },
    { name: "Millennium Bridge Area", tag: "" },
  ],

  destinations: [
    {
      name: "Lake Skadar",
      slug: "podgorica",
      tag: "30 min from TGD",
      desc: "The Balkans\u2019 largest lake. Pelicans, wine, and boat trips.",
      image: "/img/podgorica-city.webp",
    },
    {
      name: "Cetinje",
      slug: "podgorica",
      tag: "Old Royal Capital",
      desc: "Monasteries, palaces, and mountain air.",
      image: "/img/podgorica-city.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "60 min from TGD",
      desc: "Riviera beaches and vibrant old town.",
      image: "/img/budva-old-town.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "90 min from TGD",
      desc: "UNESCO walled city and fjord-like bay.",
      image: "/img/kotor-nearby.webp",
    },
    {
      name: "Durmitor / Zabljak",
      slug: "podgorica",
      tag: "Mountain North",
      desc: "Black Lake, Tara Canyon, and alpine peaks.",
      image: "/img/podgorica-city.webp",
    },
    {
      name: "Ostrog Monastery",
      slug: "podgorica",
      tag: "Cliff Monastery",
      desc: "Carved into a sheer rock face above the Zeta plain.",
      image: "/img/podgorica-city.webp",
    },
    {
      name: "Nik\u0161i\u0107",
      slug: "podgorica",
      tag: "Second City",
      desc: "Beer, lakes, and gateway to the north.",
      image: "/img/podgorica-city.webp",
    },
    {
      name: "Podgorica City",
      slug: "podgorica",
      tag: "Capital",
      desc: "Montenegro\u2019s modern capital \u2014 culture and commerce.",
      image: "/img/podgorica-city.webp",
    },
  ],
};

export default siteConfig;
