const siteConfig = {
  name: "Podgorica Airport Car Rental",
  tagline: "Your Capital, Mountain and Lake Road Trip Starts Here",
  domain: "podgoricaairportcarrental.com",
  phone: "",
  email: "info@podgoricaairportcarrental.com",
  address: "Podgorica Airport (TGD), 81304 Golubovci",

  hero: {
    headline: "Rent a Car at Podgorica Airport",
    subheadline: "Collect at Podgorica Airport (TGD) arrivals. Head straight to Skadar Lake, Ostrog Monastery, Kolašin, Žabljak or the Adriatic coast on the Smokovac–Mateševo motorway.",
    image: "/img/hero-podgorica-airport.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      typeGroup: "economy",
      name: "VW Polo",
      category: "Economy",
      tagline: "The sensible TGD-arrivals runabout for a capital base with lake and mountain day-trips",
      lede: "Light on fuel, easy to park in Podgorica's grid streets, and composed at 130 km/h on the Bar–Boljare motorway sections.",
      price: 28,
      image: "/img/fleet/vw-polo.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Bluetooth Audio","USB Charging","Central Locking","Touchscreen Display"],
      details: {
        engine: "1.0 TSI 3-cyl turbo petrol",
        power: "95 hp",
        consumption: "5.2 L/100 km",
        bootSize: "351 L",
        length: "4,074 mm",
        topSpeed: "187 km/h",
        acceleration: "10.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: true,
      bestFor: ["Couples on a week in the capital", "Day-trippers to Skadar Lake and Cetinje", "TGD arrivals heading to Ostrog Monastery"],
      suitability: "A pair collecting at TGD and basing in Podgorica or nearby, with regular runs out to Skadar, Ostrog and Kolašin — easy to park, predictable at the pump.",
      regional: "Handles the motorway climb to Kolašin without drama, threads Podgorica's grid off Bulevar Save Kovačevića, and the 5.2 L/100 km petrol keeps fuel costs in check over a multi-day hire.",
    },
    {
      id: 2,
      slug: "peugeot-308",
      typeGroup: "midsize",
      name: "Peugeot 308",
      category: "Mid-Size",
      tagline: "Diesel mid-size for the Podgorica → Žabljak and cross-border Albania/Kosovo runs",
      lede: "Long-legged BlueHDi + auto box built for the push up to Durmitor or the cross-border drive to Shkodër, Prizren or Belgrade.",
      price: 38,
      image: "/img/fleet/peugeot-308.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Automatic Transmission","Adaptive Cruise","Dual-Zone Climate","Large Boot"],
      details: {
        engine: "1.5 BlueHDi 4-cyl diesel",
        power: "130 hp",
        consumption: "4.4 L/100 km",
        bootSize: "412 L (1,309 L seats folded)",
        length: "4,367 mm",
        topSpeed: "206 km/h",
        acceleration: "10.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 8-spd auto",
      },
      popular: true,
      bestFor: ["Cross-border road-trippers","Durmitor weekenders","Four adults with full luggage"],
      suitability: "The mid-size diesel pick for anyone pairing a TGD arrival with multi-day drives to Žabljak, Shkodër or Prizren — auto gearbox and cruise control earn their keep on the Smokovac–Mateševo motorway.",
      regional: "Cruises the Smokovac–Mateševo motorway effortlessly, swallows a week of hiking kit bound for Durmitor, and covers the Podgorica → Belgrade via Bijelo Polje run on a single tank.",
    },
    {
      id: 3,
      slug: "renault-megane",
      typeGroup: "midsize",
      name: "Renault Megane",
      category: "Mid-Size",
      tagline: "Biggest-boot French mid-size — built for Skadar fishing kit and Kolašin ski loads",
      lede: "434-litre boot, quiet diesel cruising, sofa-soft damping — the mid-size wagon pick for a week based at TGD with regular inland excursions.",
      price: 36,
      image: "/img/fleet/renault-megane.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Large Boot","Bluetooth Audio","Cruise Control","Parking Sensors"],
      details: {
        engine: "1.5 Blue dCi 4-cyl diesel",
        power: "115 hp",
        consumption: "4.3 L/100 km",
        bootSize: "434 L",
        length: "4,360 mm",
        topSpeed: "195 km/h",
        acceleration: "11.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 6-spd manual",
      },
      popular: false,
      bestFor: ["Long-stay TGD renters","Skadar Lake day-trippers","Families visiting Ostrog"],
      suitability: "Renters who want more than a hatchback's packing space without the length of a full estate — ideal for Skadar fishing kit, Ostrog monastery day-bags and a cool-box for the drive back down to the capital.",
      regional: "The long-travel suspension shrugs off the patchy bitumen on the Virpazar approach to Skadar, the dCi diesel sips on the Sozina tunnel run down to Bar, and the generous boot takes two weeks of family kit plus Kolašin ski gear.",
    },
    {
      id: 4,
      slug: "kia-stonic",
      typeGroup: "suv",
      name: "Kia Stonic",
      category: "Compact Crossover",
      tagline: "Raised-ride crossover for the gravel approach to Ostrog and the Durmitor side-roads",
      lede: "A slightly higher-riding alternative to a hatchback — takes the steep cliff-road up to Ostrog and the rutted Durmitor spurs without scraping.",
      price: 40,
      image: "/img/fleet/kia-stonic.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Raised Ride Height","Apple CarPlay","Reversing Camera","Lane Keep Assist"],
      details: {
        engine: "1.0 T-GDi 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.5 L/100 km",
        bootSize: "352 L (1,155 L seats folded)",
        length: "4,140 mm",
        topSpeed: "183 km/h",
        acceleration: "10.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Weekend trippers to Ostrog","Durmitor day-trippers","Photographers chasing ridge viewpoints"],
      suitability: "Renters who want crossover sight-lines and a bit of ground clearance for the Ostrog cliff road and the Durmitor national-park side-lanes, without paying full-SUV money.",
      regional: "Higher seating position makes the switchbacks above Bogetići easier to read, the 182 mm ride height clears the loose stone on the old Ostrog pilgrim road, and the 352-litre boot handles a family's Žabljak hiking gear without folding seats.",
    },
    {
      id: 5,
      slug: "vw-golf",
      typeGroup: "midsize",
      name: "VW Golf",
      category: "Mid-Size",
      tagline: "DSG diesel all-rounder — calm cruising for the E80 / E65 and multi-day loops",
      lede: "The rational default for a TGD arrival mixing a capital base with long inland drives — refined, quick enough, and economical on the motorway.",
      price: 42,
      image: "/img/fleet/vw-golf.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["DSG Automatic", "Adaptive Cruise", "Digital Cockpit", "Apple CarPlay"],
      details: {
        engine: "2.0 L TDI diesel (Mk8)",
        power: "150 hp",
        consumption: "4.3 L/100 km",
        bootSize: "381 L (1,237 L seats folded)",
        length: "4,287 mm",
        topSpeed: "223 km/h",
        acceleration: "8.4s (0–100 km/h)",
        driveType: "Front-wheel drive, 7-spd DSG auto",
      },
      popular: false,
      bestFor: ["Couples mixing capital, canyon and coast", "Business travellers on week-long hires", "Drivers planning the Albania or Serbia border run"],
      suitability: "The default mid-size for renters who want one car that will do Podgorica's boulevards on day one and the Smokovac-Mateševo motorway to Kolašin on day four without complaint.",
      regional: "DSG picks the right ratio on the Ostrog hairpins without any thinking, the 2.0 TDI holds 130 km/h on the motorway section up to Mateševo at 4.3 L/100 km, and the cabin quiet makes the 2-hour push to Žabljak genuinely relaxing.",
    },
    {
      id: 6,
      slug: "toyota-yaris",
      typeGroup: "economy",
      name: "Toyota Yaris",
      category: "City",
      tagline: "Hybrid city car for TGD short stays — sips fuel in Podgorica traffic",
      lede: "Self-charging hybrid, short footprint, surprisingly roomy — the pick for a two- or three-night Podgorica anchor when multi-day drives aren't planned.",
      price: 30,
      image: "/img/fleet/toyota-yaris.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Hybrid Drive", "Easy Parking", "Apple CarPlay", "Reversing Camera"],
      details: {
        engine: "1.5 L hybrid petrol",
        power: "116 hp",
        consumption: "3.8 L/100 km",
        bootSize: "286 L",
        length: "3,940 mm",
        topSpeed: "175 km/h",
        acceleration: "9.7s (0–100 km/h)",
        driveType: "Front-wheel drive, e-CVT",
      },
      popular: false,
      bestFor: ["Short TGD stays", "Solo visitors watching the fuel bill", "Business arrivals with two or three nights in the capital"],
      suitability: "Two or three nights at a Podgorica hotel with short hops to Skadar or Cetinje — the hybrid Yaris parks where mid-size cars shuffle and sips 3.8 L/100 km in city traffic.",
      regional: "The self-charging hybrid drivetrain is the deciding factor: it turns Podgorica's stop-start boulevards into battery-assisted coasting, the 3.94 m length slots into any capital-centre bay, and the e-CVT makes the climb to Cetinje effortless.",
    },
    {
      id: 7,
      slug: "citroen-c3",
      typeGroup: "economy",
      name: "Citroen C3",
      category: "Economy",
      tagline: "Softest small hatch for the broken stretches around Skadar and back-road Albania detours",
      lede: "Advanced Comfort dampers iron out the patched tarmac on the Virpazar and Tuzi side-roads — the gentlest small car to collect at TGD.",
      price: 27,
      image: "/img/fleet/citroen-c3.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Advanced Comfort Seats","Bluetooth Audio","USB Charging","Lane Departure Warning"],
      details: {
        engine: "1.2 PureTech 3-cyl petrol",
        power: "83 hp",
        consumption: "5.5 L/100 km",
        bootSize: "300 L",
        length: "3,996 mm",
        topSpeed: "175 km/h",
        acceleration: "13.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Slow-touring couples","Back-road explorers","Renters prone to motion sickness"],
      suitability: "The comfort-first pick for a week out of TGD with daily slow-paced detours — Skadar villages, the Rijeka Crnojevića meander, the old road up to Cetinje.",
      regional: "The progressive hydraulic bump stops make the potholed stretches along Lake Skadar feel a size-class quieter, the low-stress 83 hp motor suits the 50 km/h rural limits, and the 4-metre length slots into any Podgorica street bay.",
    },
  ],

  features: [
    { icon: "map-pin", title: "TGD Airport Collection", description: "Your vehicle waits outside Podgorica Airport arrivals — direct access to the E80 and the Bar–Boljare motorway within minutes of landing." },
    { icon: "shield-check", title: "Comprehensive Cover", description: "Every rental includes CDW and third-party liability. Upgrade to zero excess if the Ostrog cliff road or Durmitor mountain passes make you nervous." },
    { icon: "clock", title: "Round-the-Clock Assistance", description: "Flat tyre near Virpazar? Lost a key in Kolašin? Our local team answers day and night — they know every road out of the capital." },
    { icon: "ban", title: "Transparent Pricing", description: "The figure on your confirmation is the figure at the desk. No fuel surprises, no airport levies, no extras sneaked in at pickup." },
    { icon: "refresh-cw", title: "Flexible Cancellation", description: "Plans shift — flights reschedule, weather closes mountain roads. Cancel most bookings free up to a week before your collection date." },
    { icon: "globe", title: "Cross-Border Ready", description: "Albania via Božaj / Tuzi, Kosovo through Kulina, Serbia on the E65, Croatia via Debeli Brijeg — Green Card paperwork prepared at booking time." },
  ],

  testimonials: [
    { name: "Sophie & Daniel", location: "Munich, Germany", text: "We landed at TGD and drove straight to Ostrog for sunset. The climb from Bogetići was stunning — cliff on one side, valley on the other. Next morning we took the motorway up to Kolašin. The car handled every hairpin perfectly. Seamless from start to finish.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "James Harrington", location: "Bristol, England", text: "Third time renting in Podgorica and the booking process keeps getting smoother. This time I drove south to Skadar Lake and up to Cetinje in one day. Having a car makes destinations like Ostrog and Rijeka Crnojevića actually accessible instead of theoretical.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Rossi Family", location: "Milan, Italy", text: "We arrived at Podgorica Airport and needed a car for two days. Picked up right at arrivals, visited Ostrog and Skadar, then drove the motorway to Budva. The cross-border paperwork was ready — no delays at all. Perfect family road trip.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What do I need to bring for pickup?", a: "A valid driving licence, your passport or national ID, and a physical credit card in the lead driver's name. Licences without Latin characters also require an International Driving Permit." },
    { q: "Can I cross into Albania, Serbia or other countries?", a: "Absolutely. Albania is about 40 minutes via the Božaj or Tuzi checkpoints — we include the Green Card at booking. Serbia, Kosovo, Bosnia and Croatia are also available with advance notice." },
    { q: "What age do I need to be?", a: "The minimum is 21 years old with at least two years of driving experience. Drivers under 25 pay a young-driver supplement — the exact amount depends on the vehicle category." },
    { q: "What does the rental price cover?", a: "Every booking includes CDW insurance, third-party liability, VAT, and a roadside safety kit. Most vehicles offer unlimited mileage — check the individual listing for details." },
    { q: "How do I collect the car at Podgorica Airport?", a: "A representative meets you inside the TGD arrivals area with a name board. Your car is in the terminal car park, steps away. The drive to central Podgorica is around fifteen minutes." },
    { q: "Is one-way rental possible?", a: "Yes — pick up and drop off at different locations across 28+ points in Montenegro. A one-way surcharge may apply depending on the distance between locations." },
    { q: "What if I need to cancel?", a: "Most vehicles offer free cancellation up to seven days before pickup. Premium and convertible classes require thirty days. A small processing fee applies to all cancellations." },
    { q: "Do I need a deposit?", a: "Most cars require between €100 and €350 held on a credit card. Some economy vehicles are deposit-free — these are clearly marked in your search results." },
    { q: "Is there a mileage cap?", a: "Many vehicles include unlimited mileage. Those with limits charge a per-kilometre rate beyond the allowance — always visible before you confirm." },
    { q: "Are there any surprise charges?", a: "None. The displayed price includes every tax and fee. No airport surcharges, no fuel-policy add-ons, nothing extra at the counter." },
    { q: "How much is the booking deposit?", a: "A 15–20% advance payment secures your reservation. The balance is settled directly with the rental agent when you arrive to collect the vehicle." },
    { q: "Can I rent without a credit card?", a: "A handful of vehicles are available without a credit card requirement. Look for the no-deposit filter when searching by pickup location." },
  ],

  locations: [
    { name: "Podgorica Airport", tag: "Most Popular" },
    { name: "Podgorica City", tag: "Local Pickup" },
    { name: "Skadar Lake", tag: "" },
    { name: "Kolašin", tag: "" },
    { name: "Žabljak", tag: "" },
    { name: "Budva", tag: "" },
  ],

  destinations: [
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "Most Popular",
      desc: "Land and drive — direct onto the E80 and motorway north.",
      image: "/img/podgorica-airport.webp",
    },
    {
      name: "Podgorica",
      slug: "podgorica",
      tag: "Capital City",
      desc: "Six rivers, three eras — gateway to the mountains.",
      image: "/img/podgorica-city.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "UNESCO Heritage",
      desc: "Walled Old Town at the head of the bay — 90 min from TGD.",
      image: "/img/kotor-old-town.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "60 min drive",
      desc: "Riviera beaches and a 2,500-year-old citadel.",
      image: "/img/budva-from-kotor.webp",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "100 min drive",
      desc: "Baroque waterfront and two island churches.",
      image: "/img/perast-village.webp",
    },
    {
      name: "Tivat",
      slug: "tivat",
      tag: "90 min drive",
      desc: "Porto Montenegro and the Boka Bay promenade.",
      image: "/img/porto-montenegro.webp",
    },
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "Cross-Airport",
      desc: "Coastal airport 90 min from TGD — fly in or out either way.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Dubrovnik Airport",
      slug: "dubrovnik-airport",
      tag: "Cross-Border",
      desc: "Land in Croatia, reach Podgorica in three hours.",
      image: "/img/dubrovnik-nearby.webp",
    },
  ],
};

export default siteConfig;
