const siteConfig = {
  name: "Podgorica Airport Car Rental",
  tagline: "Your Capital, Mountain and Lake Road Trip Starts Here",
  domain: "podgoricaairportcarrental.com",
  phone: "",
  email: "info@podgoricaairportcarrental.com",
  address: "Podgorica Airport (TGD), 81304 Golubovci",

  hero: {
    headline: "Rent a Car at Podgorica Airport",
    subheadline: "Collect at Podgorica Airport (TGD) arrivals. Head straight to Skadar Lake, Ostrog Monastery, Kolašin, Žabljak or the Adriatic coast on the Smokovac–Mateševo motorway.",
    image: "/img/hero-podgorica-airport.webp",
  },

  cars: [
    {
      id: 1,
      slug: "renault-clio",
      typeGroup: "economy",
      name: "Renault Clio",
      category: "Economy",
      tagline: "The low-maintenance coast-runner for a fortnight-long Podgorica base",
      lede: "Light on fuel, cheap to park at the pickup location, and comfortable on the motorway push to Podgorica or Žabljak.",
      price: 28,
      image: "/img/fleet/renault-clio.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Bluetooth Audio","USB Charging","Central Locking","Touchscreen Display"],
      details: {
        engine: "1.0 TCe 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.3 L/100 km",
        bootSize: "391 L",
        length: "4,050 mm",
        topSpeed: "188 km/h",
        acceleration: "11.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: true,
      bestFor: ["Couples on a two-week stay", "Day-trippers to Cetinje and Njeguši", "Shoppers at Risan Roman mosaics"],
      suitability: "A pair settling in Podgorica for ten to fourteen days, with regular day-trips out to Cetinje, Risan and the Lake Skadar shore, simple to park, forgiving on petrol.",
      regional: "Handles the Podgorica–Cetinje climb in third gear without drama, threads the narrow waterfront through outlying villages, and the 5.3 L/100 km petrol keeps the fuel bill predictable over a multi-week hire.",
    },
    {
      id: 2,
      slug: "peugeot-308",
      typeGroup: "midsize",
      name: "Peugeot 308",
      category: "Mid-Size",
      tagline: "Diesel mid-size for the Podgorica → Dubrovnik and Podgorica → Durmitor runs",
      lede: "Long-legged BlueHDi + auto box built for the 3-hour push up to Žabljak or the cross-border drive to Trebinje and Mostar.",
      price: 38,
      image: "/img/fleet/peugeot-308.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Automatic Transmission","Adaptive Cruise","Dual-Zone Climate","Large Boot"],
      details: {
        engine: "1.5 BlueHDi 4-cyl diesel",
        power: "130 hp",
        consumption: "4.4 L/100 km",
        bootSize: "412 L (1,309 L seats folded)",
        length: "4,367 mm",
        topSpeed: "206 km/h",
        acceleration: "10.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 8-spd auto",
      },
      popular: true,
      bestFor: ["Cross-border road-trippers","Durmitor weekenders","Four adults with full luggage"],
      suitability: "The mid-size diesel picks for anyone pairing a Podgorica base with multi-day drives inland, auto gearbox and cruise control earn their keep on the Podgorica motorway.",
      regional: "Cruises the Smokovac–Mateševo motorway section effortlessly, swallows a week of hiking kit bound for Žabljak, and covers the Podgorica → Dubrovnik via Debeli Brijeg run on half a tank.",
    },
    {
      id: 3,
      slug: "renault-megane",
      typeGroup: "midsize",
      name: "Renault Megane",
      category: "Mid-Size",
      tagline: "Biggest-boot French mid-size, built for long-stay loads and lake trips",
      lede: "434-litre boot, quiet diesel cruising, sofa-soft damping, the mid-size wagon pick for a month in the bay with regular excursions out.",
      price: 36,
      image: "/img/fleet/renault-megane.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Large Boot","Bluetooth Audio","Cruise Control","Parking Sensors"],
      details: {
        engine: "1.5 Blue dCi 4-cyl diesel",
        power: "115 hp",
        consumption: "4.3 L/100 km",
        bootSize: "434 L",
        length: "4,360 mm",
        topSpeed: "195 km/h",
        acceleration: "11.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 6-spd manual",
      },
      popular: false,
      bestFor: ["Long-stay renters","Skadar Lake day-trippers","Families visiting monasteries"],
      suitability: "Renters who want more than a hatchback's packing space without the length of a full estate, ideal for Skadar Lake fishing kit, Cetinje monastery day-bags and a cool-box for the drive home.",
      regional: "The long-travel suspension shrugs off the patchy bitumen on the old Podgorica–Budva road, the dCi diesel sips on the Sozina tunnel run, and the generous boot takes two weeks of family kit plus the laundry bag you pick up in Prčanj.",
    },
    {
      id: 4,
      slug: "kia-stonic",
      typeGroup: "suv",
      name: "Kia Stonic",
      category: "Compact Crossover",
      tagline: "Raised-ride crossover for the gravel approach to Njeguši and Lovćen",
      lede: "A slightly higher-riding alternative to a hatchback, takes the rutted spur roads around Njeguši and the Lovćen back approaches without scraping.",
      price: 40,
      image: "/img/fleet/kia-stonic.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Raised Ride Height","Apple CarPlay","Reversing Camera","Lane Keep Assist"],
      details: {
        engine: "1.0 T-GDi 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.5 L/100 km",
        bootSize: "352 L (1,155 L seats folded)",
        length: "4,140 mm",
        topSpeed: "183 km/h",
        acceleration: "10.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Weekend trippers to Njeguši","Durmitor day-trippers","Photographers chasing ridge viewpoints"],
      suitability: "Renters who want crossover sight-lines and a bit of ground clearance for the side-roads around Podgorica's upper bay and the Lovćen approach, without paying full-SUV money.",
      regional: "Higher seating position means easier viewing over region parapet walls, the 182 mm ride height clears the stone ruts on the old Njeguši ham-smoker lane, and the 352-litre boot handles a family's Durmitor hiking gear without folding seats.",
    },
    {
      id: 5,
      slug: "vw-golf",
      typeGroup: "midsize",
      name: "VW Golf",
      category: "Mid-Size",
      tagline: "DSG diesel all-rounder, calm cruising for the E80 and multi-day loops",
      lede: "The rational default for a renter mixing a Podgorica base with long inland drives, refined, quick enough, and economical on the motorway.",
      price: 42,
      image: "/img/fleet/vw-golf.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["DSG Automatic", "Adaptive Cruise", "Digital Cockpit", "Apple CarPlay"],
      details: {
        engine: "2.0 L TDI diesel (Mk8)",
        power: "150 hp",
        consumption: "4.3 L/100 km",
        bootSize: "381 L (1,237 L seats folded)",
        length: "4,287 mm",
        topSpeed: "223 km/h",
        acceleration: "8.4s (0–100 km/h)",
        driveType: "Front-wheel drive, 7-spd DSG auto",
      },
      popular: false,
      bestFor: ["Couples mixing coast and canyon", "Business travellers on week-long hires", "Drivers planning the BiH or Croatia border run"],
      suitability: "The default mid-size for renters who want one car that will do the Podgorica Old Town perimeter on day one and the Smokovac-Mateševo motorway on day four without complaint.",
      regional: "DSG picks the right ratio on the Podgorica–Lovćen hairpins without any thinking, the 2.0 TDI holds 130 km/h on the motorway section up to Podgorica at 4.3 L/100 km, and the cabin quiet makes the 3-hour push to Žabljak genuinely relaxing.",
    },
    {
      id: 6,
      slug: "fiat-500",
      typeGroup: "economy",
      name: "Fiat 500",
      category: "City",
      tagline: "Postage-stamp city car for a short Podgorica stay, slots between delivery vans",
      lede: "Tiny footprint, sunroof, hybrid-assisted 1.0, the pick for a two- or three-night Podgorica anchor when multi-day drives aren't on the schedule.",
      price: 20,
      image: "/img/fleet/fiat-500.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      details: {
        engine: "1.0 L mild-hybrid petrol",
        power: "70 hp",
        consumption: "5.4 L/100 km",
        bootSize: "185 L",
        length: "3,571 mm",
        topSpeed: "167 km/h",
        acceleration: "13.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Short city-base stays", "Solo visitors on a shoestring", "Photographers doing short hops"],
      suitability: "Two or three nights in Podgorica with short afternoon hops to Perast and Prčanj, the 500 parks where mid-size cars wave and drive past.",
      regional: "The 3.57 m length is the deciding factor: it fits the stepped terrace parking on the nearby villages waterfront and the shoulder-wide gap outside the Sea Gate that a Clio can't. Underpowered for the Lovćen climb, so pair with cable-car transfers or keep within bay limits.",
    },
    {
      id: 7,
      slug: "citroen-c3",
      typeGroup: "economy",
      name: "Citroen C3",
      category: "Economy",
      tagline: "Softest small hatch for the broken Podgorica–Risan stretch and back-road detours",
      lede: "Advanced Comfort dampers iron out the patched tarmac on the old bay road, the gentlest small car to park at the Podgorica bastions overnight.",
      price: 27,
      image: "/img/fleet/citroen-c3.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Advanced Comfort Seats","Bluetooth Audio","USB Charging","Lane Departure Warning"],
      details: {
        engine: "1.2 PureTech 3-cyl petrol",
        power: "83 hp",
        consumption: "5.5 L/100 km",
        bootSize: "300 L",
        length: "3,996 mm",
        topSpeed: "175 km/h",
        acceleration: "13.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Slow-touring couples","Back-road explorers","Renters prone to motion sickness"],
      suitability: "The comfort-first pick for a week in Podgorica with daily slow-paced detours, Risan's Roman mosaics, the Gornja Lastva hamlet above Tivat, the loop back through nearby villages.",
      regional: "The progressive hydraulic bump stops make the potholed stretch from Risan to Perast feel a size-class quieter, the low-stress 83 hp motor suits the 50 km/h bay-road limits, and the 4-metre length slots into any Old Town bastion bay.",
    },
  ],

  features: [
    { icon: "map-pin", title: "TGD Airport Collection", description: "Your vehicle waits outside Podgorica Airport arrivals, direct access to the E80 and the Bar–Boljare motorway within minutes of landing." },
    { icon: "shield-check", title: "Comprehensive Cover", description: "Every rental includes CDW and third-party liability. Upgrade to zero excess if the Ostrog cliff road or Durmitor mountain passes make you nervous." },
    { icon: "clock", title: "Round-the-Clock Assistance", description: "Flat tyre near Virpazar? Lost a key in Kolašin? Our local team answers day and night, they know every road out of the capital." },
    { icon: "ban", title: "Transparent Pricing", description: "The figure on your confirmation is the figure at the desk. No fuel surprises, no airport levies, no extras sneaked in at pickup." },
    { icon: "refresh-cw", title: "Flexible Cancellation", description: "Plans shift, flights reschedule, weather closes mountain roads. Cancel most bookings free up to a week before your collection date." },
    { icon: "globe", title: "Cross-Border Ready", description: "Albania via Božaj / Tuzi, Kosovo through Kulina, Serbia on the E65, Croatia via Debeli Brijeg, Green Card paperwork prepared at booking time." },
  ],

  testimonials: [
    { name: "Sophie & Daniel", location: "Munich, Germany", text: "We landed at TGD and drove straight to Ostrog for sunset. The climb from Bogetići was stunning, cliff on one side, valley on the other. Next morning we took the motorway up to Kolašin. The car handled every hairpin perfectly. Seamless from start to finish.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "James Harrington", location: "Bristol, England", text: "Third time renting in Podgorica and the booking process keeps getting smoother. This time I drove south to Skadar Lake and up to Cetinje in one day. Having a car makes destinations like Ostrog and Rijeka Crnojevića actually accessible instead of theoretical.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Rossi Family", location: "Milan, Italy", text: "We arrived at Podgorica Airport and needed a car for two days. Picked up right at arrivals, visited Ostrog and Skadar, then drove the motorway to Budva. The cross-border paperwork was ready, no delays at all. Perfect family road trip.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What do I need to bring for pickup?", a: "A valid driving licence, your passport or national ID, and a physical credit card in the lead driver's name. Licences without Latin characters also require an International Driving Permit." },
    { q: "Can I cross into Albania, Serbia or other countries?", a: "Absolutely. Albania is about 40 minutes via the Božaj or Tuzi checkpoints, we include the Green Card at booking. Serbia, Kosovo, Bosnia and Croatia are also available with advance notice." },
    { q: "What age do I need to be?", a: "The minimum is 21 years old with at least two years of driving experience. Drivers under 25 pay a young-driver supplement, the exact amount depends on the vehicle category." },
    { q: "What does the rental price cover?", a: "Every booking includes CDW insurance, third-party liability, VAT, and a roadside safety kit. Most vehicles offer unlimited mileage, check the individual listing for details." },
    { q: "How do I collect the car at Podgorica Airport?", a: "A representative meets you inside the TGD arrivals area with a name board. Your car is in the terminal car park, steps away. The drive to central Podgorica is around fifteen minutes." },
    { q: "What if I need to cancel?", a: "Most vehicles offer free cancellation up to seven days before pickup. Premium and convertible classes require thirty days. A small processing fee applies to all cancellations." },
    { q: "Do I need a deposit?", a: "Most cars require between €100 and €350 held on a credit card. Some economy vehicles are deposit-free, these are clearly marked in your search results." },
    { q: "Is there a mileage cap?", a: "Many vehicles include unlimited mileage. Those with limits charge a per-kilometre rate beyond the allowance, always visible before you confirm." },
    { q: "Are there any surprise charges?", a: "None. The displayed price includes every tax and fee. No airport surcharges, no fuel-policy add-ons, nothing extra at the counter." },
    { q: "How much is the booking deposit?", a: "A 15–20% advance payment secures your reservation. The balance is settled directly with the rental agent when you arrive to collect the vehicle." },
    { q: "Can I rent without a credit card?", a: "A handful of vehicles are available without a credit card requirement. Look for the no-deposit filter when searching by pickup location." },
  ],

  locations: [
    { name: "Podgorica Airport", tag: "Most Popular" },
    { name: "Podgorica City", tag: "Local Pickup" },
    { name: "Skadar Lake", tag: "" },
    { name: "Kolašin", tag: "" },
    { name: "Žabljak", tag: "" },
    { name: "Budva", tag: "" },
  ],

  destinations: [
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "Most Popular",
      desc: "Land and drive, direct onto the E80 and motorway north.",
      image: "/img/podgorica-airport.webp",
    },
    {
      name: "Podgorica",
      slug: "podgorica",
      tag: "Capital City",
      desc: "Six rivers, three eras, gateway to the mountains.",
      image: "/img/podgorica-city.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "UNESCO Heritage",
      desc: "Walled Old Town at the head of the bay, 90 min from TGD.",
      image: "/img/kotor-old-town.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "60 min drive",
      desc: "Riviera beaches and a 2,500-year-old citadel.",
      image: "/img/budva-from-kotor.webp",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "100 min drive",
      desc: "Baroque waterfront and two island churches.",
      image: "/img/perast-village.webp",
    },
    {
      name: "Tivat",
      slug: "tivat",
      tag: "90 min drive",
      desc: "Porto Montenegro and the Boka Bay promenade.",
      image: "/img/porto-montenegro.webp",
    },
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "Cross-Airport",
      desc: "Coastal airport 90 min from TGD, fly in or out either way.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Dubrovnik Airport",
      slug: "dubrovnik-airport",
      tag: "Cross-Border",
      desc: "Land in Croatia, reach Podgorica in three hours.",
      image: "/img/dubrovnik-nearby.webp",
    },
  ],
};

export default siteConfig;
